export const site = {
  name: "RYY Abogados",
  legalName: "Rivas & Yuraszeck Abogados",
  shortName: "RYY",
  alternateNames: [
    "Rivas Legal",
    "Rivas Yuraszeck",
    "RYY",
    "RYY Abogados Chile",
  ],
  url: "https://ryyabogados.cl",
  locale: "es-CL",
  language: "es",
  country: "CL",
  region: "Región Metropolitana",
  description:
    "Estudio jurídico chileno con +10 años de experiencia en derecho laboral para empresas. Especialistas en litigios laborales, Ley Karin, compliance, negociación colectiva, migraciones y protección de datos. Asesoría empresarial permanente en Santiago de Chile.",
  shortDescription:
    "Estudio jurídico chileno especializado en derecho laboral, compliance y asesoría empresarial.",
  tagline: "Derecho laboral. Sin solemnidad innecesaria.",
  keywords: [
    "abogados laborales Chile",
    "estudio jurídico Santiago",
    "asesoría laboral empresas",
    "abogados laborales empresas Chile",
    "derecho laboral Chile",
    "Ley Karin",
    "Ley Karin Chile",
    "compliance laboral",
    "compliance laboral Chile",
    "modelo de prevención del delito",
    "reglamento interno orden higiene y seguridad",
    "RIOHS",
    "negociación colectiva",
    "negociación colectiva Chile",
    "litigios laborales",
    "juicios laborales",
    "tribunales del trabajo",
    "migraciones laborales",
    "visas de trabajo Chile",
    "protección de datos personales",
    "Ley 19.628",
    "Ley 21.643",
    "derechos fundamentales",
    "salud ocupacional",
    "accidentes del trabajo",
    "enfermedades profesionales",
    "asesoría sindical",
    "investigaciones internas",
    "RRHH legal",
    "Rivas Legal",
    "Rivas y Yuraszeck",
    "RYY Abogados",
    "César Rivas Calderón",
    "Josefa Yuraszeck Bravo",
  ],
  founded: "2015",
  priceRange: "$$$",
  areaServed: ["Chile", "Santiago", "Región Metropolitana"],
  logos: {
    light:
      "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1777776229/icoW1_dat3ng.png",
    dark: "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1777776230/icoB1_roek5w.png",
  },
  banner:
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1779852990/ChatGPT_Image_26_may_2026_23_35_59_1_m5imjb.png",
  hero: {
    bg: "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1778593188/ChatGPT_Image_12_may_2026_09_38_07_jl6kwf.png",
  },
  contact: {
    phone: "+56 9 7766 0481",
    phoneIntl: "+56977660481",
    whatsapp: "https://wa.me/56977660481",
    email: "contacto@ryyabogados.cl",
    address: "Santiago de Chile",
    addressLocality: "Santiago",
    addressRegion: "Región Metropolitana",
    addressCountry: "CL",
    linkedin: "https://www.linkedin.com/company/ryy-abogados",
  },
  nav: [
    { label: "Equipo", href: "#equipo" },
    { label: "Servicios", href: "#servicios" },
    { label: "Proceso", href: "#proceso" },
    { label: "Insights", href: "#insights" },
    { label: "Contacto", href: "#contacto" },
  ],
  consultTypes: [
    "Asesoría Laboral",
    "Litigios",
    "Compliance Laboral",
    "Migraciones",
    "Negociación Colectiva",
    "Capacitaciones",
    "Otro",
  ],
  companySizes: ["1-10", "11-50", "51-200", "200+"] as const,
} as const;
