export const site = {
  name: "RY Legal",
  legalName: "Rivas & Yuraszeck Abogados",
  shortName: "RY Legal",
  alternateNames: [
    "Rivas & Yuraszeck Abogados",
    "Rivas Yuraszeck",
    "RYY Abogados",
    "RY Legal Chile",
  ],
  url: "https://rylegal.cl",
  locale: "es-CL",
  language: "es",
  country: "CL",
  region: "Región Metropolitana",
  description:
    "Estudio jurídico chileno con +10 años de experiencia en derecho laboral para empresas. Especialistas en litigios laborales, Ley Karin, compliance, negociación colectiva, migraciones y protección de datos. Asesoría empresarial permanente en Santiago de Chile.",
  shortDescription:
    "Estudio jurídico chileno especializado en derecho laboral, compliance y asesoría empresarial.",
  tagline: "Derecho laboral. Sin solemnidad innecesaria.",
  keywords: [
    "abogados laborales Chile",
    "estudio jurídico Santiago",
    "asesoría laboral empresas",
    "abogados laborales empresas Chile",
    "derecho laboral Chile",
    "Ley Karin",
    "Ley Karin Chile",
    "compliance laboral",
    "compliance laboral Chile",
    "modelo de prevención del delito",
    "reglamento interno orden higiene y seguridad",
    "RIOHS",
    "negociación colectiva",
    "negociación colectiva Chile",
    "litigios laborales",
    "juicios laborales",
    "tribunales del trabajo",
    "migraciones laborales",
    "visas de trabajo Chile",
    "protección de datos personales",
    "Ley 19.628",
    "Ley 21.643",
    "derechos fundamentales",
    "salud ocupacional",
    "accidentes del trabajo",
    "enfermedades profesionales",
    "asesoría sindical",
    "investigaciones internas",
    "RRHH legal",
    "RY Legal",
    "RY Legal Chile",
    "Rivas y Yuraszeck",
    "RYY Abogados",
    "César Rivas Calderón",
    "Josefa Yuraszeck Bravo",
  ],
  founded: "2015",
  priceRange: "$$$",
  areaServed: ["Chile", "Santiago", "Región Metropolitana"],
  logos: {
    light:
      "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780607887/icoLig_kmkt7v.png",
    dark: "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780607888/icoDark_p02cqp.png",
  },
  // Favicon / app icon
  icon: "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780606918/iconICO_nufvw0.png",
  // Cinematic backdrop used behind the loader
  banner:
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1779852990/ChatGPT_Image_26_may_2026_23_35_59_1_m5imjb.png",
  // Social share card (Open Graph / Twitter) shown when the link is shared
  ogImage:
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780854681/ChatGPT_Image_7_jun_2026_13_50_51_1_tvctgp.png",
  // Logos of companies that have trusted the firm — rendered in a marquee
  clients: [
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780606917/icon12_oqqfpz.png",
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780606918/icon11_vh7hha.png",
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780606918/icon9_jiowju.png",
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780606918/icon8_duwlah.png",
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780606918/icon10_dgiei6.png",
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780606918/icon7_hvzu2p.png",
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780606918/icon6_psdo6v.png",
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780606918/icon5_hyghsh.png",
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780606919/icon4_lpu1of.png",
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780606919/icon1_mbasr4.png",
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780606919/icon2_amzx5i.png",
    "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1780606919/icon3_d15hox.png",
  ],
  hero: {
    bg: "https://res.cloudinary.com/dg1x0cwdc/image/upload/v1778593188/ChatGPT_Image_12_may_2026_09_38_07_jl6kwf.png",
  },
  contact: {
    phone: "+56 9 6684 4283",
    phoneIntl: "+56966844283",
    whatsapp: "https://wa.me/56966844283",
    email: "info@rylegal.cl",
    booking:
      "https://outlook.office.com/bookwithme/user/20a81cc407664665855b1eb45f2a7482@rivaslegal.cl/meetingtype/vXHphFMulUKfxHQKGezNLw2?anonymous&ismsaljsauthenabled&ep=mlink",
    address: "Santiago de Chile",
    addressLocality: "Santiago",
    addressRegion: "Región Metropolitana",
    addressCountry: "CL",
    linkedin: "https://www.linkedin.com/company/ryy-abogados",
  },
  nav: [
    { label: "Servicios", href: "/#servicios" },
    { label: "Nosotros", href: "/sobre-nosotros" },
    { label: "Proceso", href: "/#proceso" },
    { label: "Insights", href: "/#insights" },
    { label: "Contacto", href: "/#contacto" },
  ],
  consultTypes: [
    "Asesoría Laboral",
    "Litigios",
    "Compliance Laboral",
    "Migraciones",
    "Negociación Colectiva",
    "Capacitaciones",
    "Otro",
  ],
  companySizes: ["1-10", "11-50", "51-200", "200+"] as const,
} as const;
